### PR TITLE
Fix dynamic value for host in ingress

### PR DESCRIPTION
**Pull request by jnbptstm**
Replace `host = rule.host` by `host = rule.value.host` in ingress.tf to fix error while creating Ingress.

### CODE REVIEW

**Comment by patoarvizu** [comment]
Hey @jnbptstm, just out of curiosity, what version of Terraform are you running? I created this module when the latest version was 0.12 or something like that, when dynamic blocks had just been introduced. I'm surprised this hasn't been an issue before (although admittedly this module isn't very popular), so I'm just trying to figure out if it's just something I got lucky with.

**Comment by jnbptstm** [comment]
Hi @patoarvizu , I'm using v1.2.4 but I get the same error with v0.15.0.

**Comment by patoarvizu** [comment]
Ah alright, thanks. I'll approve and merge. I'm at work so I'm not going to be able to make a new release today, but I'll get it done as soon as possible!

**Review by patoarvizu — APPROVED** [review]
👍

**Comment by jnbptstm** [comment]
Thanks :)

**Pull request merged**
