### PR TITLE
Fix for_each with null value and remove deprecated argument 

### PR DESCRIPTION
**Pull request by jnbptstm**
### Fix `for_each` with `null` value
Due to my previous PR #6  this error occured ^^' :
```
│ Error: Invalid dynamic for_each value
│ 
│   on .terraform/modules/notary/ingress.tf line 28, in resource "kubernetes_ingress" "ingress":
│   28:       for_each = var.ingress_tls_hosts
│     ├────────────────
│     │ var.ingress_tls_hosts is null
│ 
│ Cannot use a null value in for_each.
```

### Remove duplicated arguments
Warnings triggered :
```
│ Warning: Argument is deprecated
│ 
│   with module.notary_generated-certificates.tls_cert_request.signer,
│   on .terraform/modules/notary_generated-certificates/modules/generated-certificates/cert-requests.tf line 11, in resource "tls_cert_request" "signer":
│   11:   key_algorithm = tls_private_key.signer.algorithm
│ 
│ This is now ignored, as the key algorithm is inferred from the `private_key_pem`.
```

### CODE REVIEW

**Comment by jnbptstm** [comment]
This attribute is deprecated since version 3.2.0 of TLS provider : https://registry.terraform.io/providers/hashicorp/tls/3.2.0/docs/resources/cert_request
Before, this attribute is mandatory. I can revert these deletions if toi want.

**Comment by patoarvizu** [comment]
I think it's fine to delete if they're deprecated, but would it destroy/replace existing certificates created with earlier versions?

**Comment by jnbptstm** [comment]
I just tried with and no, it doesn't replace/destroy existing `ca_cert_pem`, `server_cert_pem`, `signer_cert_pem` certificates :)

**Comment by patoarvizu** [comment]
Alright great! I'm trying to decide if it's worth it or necessary to add an explicit constraint on the version of the `tls` provider. I don't think this module has many users, but if anybody is upgrading but has a pinned dependency on an older version of the `tls` provider it might break, no?

**Comment by jnbptstm** [comment]
Well, this 3.2.0 version is only 3 months old. It would maybe be better to wait few more months. At the end, it's not a critical issue.

**Comment by patoarvizu** [comment]
Yeah ok, let's roll that back and wait a little longer to make those changes then.

**Comment by jnbptstm** [comment]
Done :)

**Comment by patoarvizu** [comment]
Alright, awesome! Feel free to create an issue regarding the deprecation of the fields and we can come back to it later.

Approving/merging now...

**Pull request merged**
